"""nullabe fields

Revision ID: 89922740d18b
Revises: c105b8d015cf
Create Date: 2024-03-06 15:04:02.172394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89922740d18b'
down_revision = 'c105b8d015cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('current_status',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('actual_ending_trl',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('actual_ending_trl',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('current_status',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)

    # ### end Alembic commands ###
